version: '3.1'

services:

  nginx:
    build: .
    image: arvato/wordpress
    restart: always
    command: /scripts/run-nginx.sh
    user: "33:33"
    ports:
      - 8080:8080
    volumes:
      - ${PWD}/conf/nginx.conf:/etc/nginx/nginx.conf
    links:
      - php-fpm

  php-fpm:
    build: .
    image: arvato/wordpress
    restart: always
    command: /scripts/run-php.sh
    user: "33:33"
    ports:
      - 9000:9000
    volumes:
      - ${PWD}/conf/fpm-pool.conf:/etc/php/7.2/fpm/pool.d/www.conf
      - ${PWD}/conf/fpm.conf:/etc/php/7.2/fpm/php-fpm.conf
#      - ${PWD}/src/wp-config.php:/app/wp-config.php
#      - ${PWD}/src/amazon-s3-and-cloudfront-tweaks.php:/app/wp-content/plugins/amazon-s3-and-cloudfront-tweaks.php
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_DATABASE: exampledb
      USE_MINIO: "true"
      MINIO_HOST: minio
      MINIO_PORT: 54321
      MINIO_URL_DOMAIN: localhost:54321
      AWS_ACCESS_KEY: abcdef
      AWS_SECRET_KEY: 12345678
      WP_OFFLOAD_DOMAIN: cloudfront
      WP_OFFLOAD_CLOUDFRONT: localhost:54321
      WP_OFFLOAD_BUCKET: wordpress
    links:
      - mysql
      - minio

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

  minio:
    image: minio/minio
    command:
     - server
     - --address
     - :54321
     - /data
    restart: always
    ports:
      - 54321:54321
    environment:
      MINIO_ACCESS_KEY: abcdef
      MINIO_SECRET_KEY: 12345678

  minio-setup:
    image: minio/mc
    restart: on-failure
    entrypoint: >
        /bin/sh -c "
          echo Waiting for minio service to start...;
          while ! nc -z minio 54321;
          do
            sleep 1;
          done;
          echo Connected!;
          mc config host add myminio http://minio:54321 abcdef 12345678;
          /usr/bin/mc mb myminio/wordpress;
          /usr/bin/mc policy set download myminio/wordpress;
          exit 0;
        "
    restart: "no"
    environment:
      MINIO_ACCESS_KEY: abcdef
      MINIO_SECRET_KEY: 12345678
      MINIO_HOST: minio
      MINIO_PORT: 54321
      SLEEP: 20
    links:
      - minio

  preinstall-hook:
    build: .
    image: arvato/wordpress
    restart: "no"
    command: /scripts/preinstall-hook.sh
    user: "33:33"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_DATABASE: exampledb
      WORDPRESS_BLOGNAME: toller Blog
      WORDPRESS_BLOGURL: example.loc
      WORDPRESS_USERNAME: admin
      WORDPRESS_PASSWORD: daAfG3423sf
      WORDPRESS_EMAIL: admin@example.loc
      WP_PLUGINS: "amazon-s3-and-cloudfront amazon-s3-and-cloudfront-tweaks"
      SLEEP: 10
    links:
      - mysql

  postinstall-hook:
    build: .
    image: arvato/wordpress
    restart: "no"
    command: /scripts/preinstall-hook.sh
    user: "33:33"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_DATABASE: exampledb
      WORDPRESS_BLOGNAME: toller Blog
      WORDPRESS_BLOGURL: example.loc
      WORDPRESS_USERNAME: admin
      WORDPRESS_PASSWORD: daAfG3423sf
      WORDPRESS_EMAIL: admin@example.loc
      WP_PLUGINS: "amazon-s3-and-cloudfront amazon-s3-and-cloudfront-tweaks"
      SLEEP: 20
    links:
      - mysql

  run-cron:
    build: .
    image: arvato/wordpress
    restart: "no"
    command: /scripts/run-cron.sh
    user: "33:33"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_DATABASE: exampledb
      SLEEP: 30
    links:
      - mysql