version: '3.1'

services:

  nginx:
    build: .
    restart: always
    command: /run-nginx.sh
    user: "33:33"
    ports:
      - 8080:8080
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
    links:
      - php-fpm
      
  php-fpm:
    build: .
    restart: always
    command: /run-php.sh
    user: "33:33"
    ports:
      - 9000:9000
    volumes:
      - ${PWD}/fpm-pool.conf:/etc/php/7.2/fpm/pool.d/www.conf  
      - ${PWD}/fpm.conf:/etc/php/7.2/fpm/php-fpm.conf  
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_DATABASE: exampledb
    links:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      
  install-core:
    build: .
    restart: "no"
    command: /install-core.sh
    user: "33:33"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_DATABASE: exampledb
      WORDPRESS_BLOGNAME: toller Blog
      WORDPRESS_BLOGURL: example.loc
      WORDPRESS_USERNAME: admin
      WORDPRESS_PASSWORD: daAfG3423sf
      WORDPRESS_EMAIL: admin@example.loc
    links:
      - mysql      
      
  activate-plugins:
    build: .
    restart: "no"
    command: /activate-plugins.sh
    user: "33:33"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_DATABASE: exampledb
    links:
      - mysql
      
  sut:
    depends_on: 
    - nginx
    - php-fpm
    - mysql
    links:
    - nginx
    - php-fpm
    - mysql
    image: chef/inspec
    volumes:
     - .:/share/:ro
    command: exec tests